services:
  terminology-service:
      image: "ghcr.io/itcr-uni-luebeck/termite:0.2.1-experimental"
      ports:
        - "${TERMINOLOGY_SERVICE_PORT:-8093}:8083"
      environment:
        TERMINOLOGY_SERVICE_PORT: 8083
      volumes:
        - ${VALUE_SET_DIRECTORY:-./value_sets}:/app/value_sets
        - ${CODE_SYSTEM_DIRECTORY:-./code_systems}:/app/code_systems
      healthcheck:
        test: curl --fail http://terminology-service:8083/fhir/metadata || exit 1
        interval: 5s
        retries: 20
        start_period: 20s
        timeout: 5s
